# Page settings

baseURL = "https://dteklavya.github.io/"
languageCode = "en"
title = ""
theme = "devresume"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Rajesh Pethe"
        tagline = "Senior Software Engineer"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Indore, India"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+91 95112 34092"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "rajesh.pethe@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "https://eklavvya.hashnode.dev/"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python/Django/FastAPI"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Docker, Kubernetes, Terraform, AWS"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Relentless problem solver"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BSc in Mathematics"
        university = "Guru Ghasidas University"
        dates = "1993 - 1996"
        [[params.education.list]]
        degree = "Diploma in Computer Programming and Applications"
        university = "Guru Ghasidas University"
        dates = "1996 - 1997"
        [[params.education.list]]
        degree = "Programming in 'C' Language/Shell Programming in Unix OS"
        university = "DOEACC"
        dates = "2003"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Hindi"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Yoga"
        [[params.interests.list]]
        name = "Long Drives"
        [[params.interests.list]]
        name = "Traveling"
        [[params.interests.list]]
        name = "Food"








    [params.summary]
        enable = true
        text = "I'm a hands-on software engineer with over 18 years of experience solving real-world problems with code. I’ve spent most of that time building web applications, backend systems, and automation tools — often using Python, Django, REST, and a healthy mix of SQL and shell scripts on Linux.\n\nAlong the way, I’ve also picked up frontend work with Angular and React, and built infrastructure using Docker, Kubernetes, AWS, and Terraform. I wouldn’t call myself a DevOps engineer, but I do believe in owning the full stack — from writing the API to making sure it runs smoothly in production.\n\nI’ve worked in all kinds of teams — large, small, remote, distributed, fast-paced, slow-paced. For the last few years, I’ve been freelancing, which has been both freeing and demanding in the best possible way. It’s pushed me to keep learning, stay sharp, and step outside my comfort zone. I love the mix of flexibility and challenge it brings."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Freelance Software Engineer"
        dates = "2010 - Present"
        company = "Various Clients"
        details = "Over the past many years, I’ve worked as an independent consultant and freelance engineer, helping startups and small teams bring their ideas to life — or make their systems more reliable, secure, and scalable. While the core of my work has centered around backend development (mostly Python/Django and FastAPI), the projects themselves have been quite varied:"
        [[params.experience.list.items]]
        details = "Earned repeat engagements from multiple clients"
        [[params.experience.list.items]]
        details = "Built long-term trust with remote teams across time zones"
        [[params.experience.list.items]]
        details = "Handled end-to-end ownership — from architecture and development to deployment, debugging, and handover documentation."
        [[params.experience.list.items]]
        details = "Initiated improvements in performance, deployment workflows, and security for several existing codebase I inherited."
        [[params.experience.list.items]]
        details = "Published reusable internal tools that saved clients time in future projects."

        [[params.experience.list]]
        title = "Senior Associate"
        dates = "2010 - 2010"
        company = "JP Morgan Chase"
        details = "Involved in design, development and maintenance of secure compliance monitoring tools for Investment Bank’s Technology group."
        [[params.experience.list.items]]
        details = "Excelled at developing secure and high performance Perl based backend tools."

        [[params.experience.list]]
        title = "Technical Lead"
        dates = "2008 - 2010"
        company = "InfoStep Inc"
        details = "Team Lead for development and maintenance of Globalware Solutions e-commerce SASS portal, was a single point of contact for all software issues."
        [[params.experience.list.items]]
        details = "Improved store deployment processes using ingenious and new ways."
        [[params.experience.list.items]]
        details = "Improved customer experience with upgraded customer service portal."
        [[params.experience.list.items]]
        details = "Tech Stack: Perl, Oracle DBMS."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2006 - 2008"
        company = "Oracle India Pvt. Ltd."
        details = "Developed back-end tools and packaging to monitor health of infrastructure in Oracle's infrastructure management system."




    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Dev.to Challenge"
        meta = "Open Source"
        tagline = "Built a microservice to detect phishing emails using a combination of heuristics and ML-based intent classification — delivering explainable results that clients could actually trust."

        [[params.projects.list]]
        title = "Automating CS Workflows"
        meta = "Pivotal Energy Solutions"
        tagline = "Designed context-aware REST APIs and automated workflows for use cases that previously required manual intervention."

        [[params.projects.list]]
        title = "Floor plan laid bare"
        meta = "Pivotal Energy Solutions"
        tagline = "Developed full-stack applications, including a floor plan rendering app with Angular + Django REST — transforming raw architectural data into deep interactive insights."

        [[params.projects.list]]
        title = "Re-design ETL pipeline"
        meta = "Collective2"
        tagline = "Re-engineered a complex, bidirectional ETL pipeline using Django serializers to validate and move data between multiple heterogeneous systems."

        [[params.projects.list]]
        title = "Physical docs to Paperless"
        meta = "Jain Associates"
        tagline = "Implemented document management system for physical documents resulting in a searchable archive. Managed deployment on AWS using Terraform."

        [[params.projects.list]]
        title = "Explorations"
        meta = "Open Source"
        tagline = "Created APIs for document management, translation (Bhashini), and Twitter OAuth — many of which were turned into reusable packages or pluggable Django apps."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/username"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/username"
        title = "@username"





